from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelInputText = QtWidgets.QLabel(self.centralwidget)
        self.LabelInputText.setGeometry(QtCore.QRect(230, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelInputText.setFont(font)
        self.LabelInputText.setObjectName("LabelInputText")
        self.TextEditInputText = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditInputText.setGeometry(QtCore.QRect(147, 45, 351, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditInputText.setFont(font)
        self.TextEditInputText.setObjectName("TextEditInputText")
        self.SpinBoxR = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxR.setGeometry(QtCore.QRect(50, 50, 50, 25))
        self.SpinBoxR.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpinBoxR.setFont(font)
        self.SpinBoxR.setReadOnly(False)
        self.SpinBoxR.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.SpinBoxR.setKeyboardTracking(False)
        self.SpinBoxR.setMinimum(2)
        self.SpinBoxR.setObjectName("SpinBoxR")
        self.PushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.PushButtonStart.setGeometry(QtCore.QRect(17, 175, 531, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButtonStart.setFont(font)
        self.PushButtonStart.setObjectName("PushButtonStart")
        self.LabelN = QtWidgets.QLabel(self.centralwidget)
        self.LabelN.setGeometry(QtCore.QRect(20, 50, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelN.setFont(font)
        self.LabelN.setObjectName("LabelN")
        self.LabelN.setEnabled(False)
        self.LabelOutputBinaryTextIn = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputBinaryTextIn.setGeometry(QtCore.QRect(174, 285, 210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputBinaryTextIn.setFont(font)
        self.LabelOutputBinaryTextIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelOutputBinaryTextIn.setObjectName("LabelOutputBinaryTextIn")
        self.TextEditOutputBinaryTextIn = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputBinaryTextIn.setGeometry(QtCore.QRect(10, 315, 538, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputBinaryTextIn.setFont(font)
        self.TextEditOutputBinaryTextIn.setObjectName("TextEditOutputBinaryTextIn")
        self.LabelCodeSubwords = QtWidgets.QLabel(self.centralwidget)
        self.LabelCodeSubwords.setGeometry(QtCore.QRect(770, 30, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelCodeSubwords.setFont(font)
        self.LabelCodeSubwords.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelCodeSubwords.setObjectName("LabelCodeSubwords")
        self.LabelSubmessages = QtWidgets.QLabel(self.centralwidget)
        self.LabelSubmessages.setGeometry(QtCore.QRect(760, 180, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelSubmessages.setFont(font)
        self.LabelSubmessages.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelSubmessages.setObjectName("LabelSubmessages")
        self.LabelOutputText = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputText.setGeometry(QtCore.QRect(204, 215, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputText.setFont(font)
        self.LabelOutputText.setObjectName("LabelOutputText")
        self.TextEditOutputText = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputText.setGeometry(QtCore.QRect(10, 245, 538, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputText.setFont(font)
        self.TextEditOutputText.setObjectName("TextEditOutputText")
        self.LabelOutputBinaryTextOut = QtWidgets.QLabel(self.centralwidget)
        self.LabelOutputBinaryTextOut.setGeometry(QtCore.QRect(722, 285, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelOutputBinaryTextOut.setFont(font)
        self.LabelOutputBinaryTextOut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelOutputBinaryTextOut.setObjectName("LabelOutputBinaryTextOut")
        self.TextEditOutputBinaryTextOut = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditOutputBinaryTextOut.setGeometry(QtCore.QRect(558, 315, 538, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditOutputBinaryTextOut.setFont(font)
        self.TextEditOutputBinaryTextOut.setObjectName("TextEditOutputBinaryTextOut")
        self.TableWidgetCodeSubwordsOrigins = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetCodeSubwordsOrigins.setGeometry(QtCore.QRect(560, 70, 538, 65))
        self.TableWidgetCodeSubwordsOrigins.setObjectName("TableWidgetCodeSubwordsOrigins")
        self.TableWidgetCodeSubwordsOrigins.setColumnCount(0)
        self.TableWidgetCodeSubwordsOrigins.setRowCount(0)
        self.TableWidgetSubmessages = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidgetSubmessages.setGeometry(QtCore.QRect(558, 210, 538, 65))
        self.TableWidgetSubmessages.setObjectName("TableWidgetSubmessages")
        self.TableWidgetSubmessages.setColumnCount(0)
        self.TableWidgetSubmessages.setRowCount(0)
        self.RadioButtonPlynom = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonPlynom.setGeometry(QtCore.QRect(20, 10, 41, 21))
        self.RadioButtonPlynom.setObjectName("RadioButtonPlynom")
        self.RadioButtonMatrix = QtWidgets.QRadioButton(self.centralwidget)
        self.RadioButtonMatrix.setGeometry(QtCore.QRect(90, 10, 41, 21))
        self.RadioButtonMatrix.setObjectName("RadioButtonMatrix")
        self.TextEditInputPolynomOrMatrixLine = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEditInputPolynomOrMatrixLine.setGeometry(QtCore.QRect(20, 120, 521, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEditInputPolynomOrMatrixLine.setFont(font)
        self.TextEditInputPolynomOrMatrixLine.setObjectName("TextEditInputPolynomOrMatrixLine")
        self.LabelInputPolynomOrMatrixLine = QtWidgets.QLabel(self.centralwidget)
        self.LabelInputPolynomOrMatrixLine.setGeometry(QtCore.QRect(170, 90, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelInputPolynomOrMatrixLine.setFont(font)
        self.LabelInputPolynomOrMatrixLine.setObjectName("LabelInputPolynomOrMatrixLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cyclic codec"))
        self.LabelInputText.setText(_translate("MainWindow", "Введите входное сообщение"))
        self.PushButtonStart.setText(_translate("MainWindow", "Запустить работу кодека"))
        self.LabelN.setText(_translate("MainWindow", "n ="))
        self.LabelOutputBinaryTextIn.setText(_translate("MainWindow", "Информационное слово (входное)"))
        self.LabelCodeSubwords.setText(_translate("MainWindow", "Кодовые подслова"))
        self.LabelSubmessages.setText(_translate("MainWindow", "Подслова сообщения"))
        self.LabelOutputText.setText(_translate("MainWindow", "Выходное сообщение"))
        self.LabelOutputBinaryTextOut.setText(_translate("MainWindow", "Информационное слово (выходное)"))
        self.RadioButtonPlynom.setText(_translate("MainWindow", "g(x)"))
        self.RadioButtonMatrix.setText(_translate("MainWindow", "G"))
        self.LabelInputPolynomOrMatrixLine.setText(_translate("MainWindow", "Введите полином/1-ю строку матрицы"))

